### ISSUE TITLE
Querying the trained model

### ISSUE THREAD

**Issue by stephanheinemann** [SJrX/SMAC#3]
After having trained the model, I am looking for a method to query a given ProblemInstance.
I am looking for something like

ParameterConfiguration pc = runHistory.query(ProblemInstance pi)

SMAC allows me to validate ParameterConfigurations for ProblemInstances but this is not quite what i am looking for.
The closest method I could find is

public List<ParameterConfiguration> selectChallengersWithEI(int numChallengers)

but it does not allow me to get a suitable predicted configuration for an arbitrary ProblemInstance.
I was not able to find anything in the manual either.
What do I need to do to obtain a suggested ParameterConfugration for a given ProblemInstance?

**Comment by frank-hutter** [comment]
Sorry, I think you’re confused; while it internally uses the concept of
instances for variance reduction, SMAC outputs a single configuration that
is good on average across instances, not a mapping from an instance to a
configuration. For the latter, you’d like to, e.g., use Hydra:
https://www.cs.ubc.ca/~hoos/Publ/XuEtAl10.pdf

**Comment by stephanheinemann** [comment]
Thanks Frank, Hydra might be an option but I think SMAC is still useful for me since I can associate an arbitrary problem instance to the set of training instances using domain knowledge about their features. If I have distinct problem sets, then I could use the incumbent of the associated set as the answer to my query.

Thanks again, Stephan

Sent from my iPhone

On Oct 9, 2021, at 13:27, Frank ***@***.******@***.***>> wrote:


Sorry, I think you’re confused; while it internally uses the concept of
instances for variance reduction, SMAC outputs a single configuration that
is good on average across instances, not a mapping from an instance to a
configuration. For the latter, you’d like to, e.g., use Hydra:
https://www.cs.ubc.ca/~hoos/Publ/XuEtAl10.pdf
